name: autonomous_fund_goerli
author: balancer
version: 0.1.0
description: A set of agents implementing the Autonomous Fund.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeie36flrik7sho37ynqzv7vc4thd5daw7h3af6fvi4o467fddbwgte
fingerprint_ignore_patterns: []
agent: balancer/autonomous_fund:0.1.0:bafybeiayhrdf7fvk7u5xdefoopomqecirz3fkrf7ljswylmoygudej5klu
number_of_agents: 4
deployment: {}
---
public_id: balancer/autonomous_fund_abci:0.1.0
type: skill
extra:
  params_args:
    args:
      setup: &id001
        safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:0xD1A2679e3455a018d9e0D11edb873e7C5B5d831e}
        all_participants: ${ALL_PARTICIPANTS:list:["0x0000000000000000000000000000000000000000"]}
      pool_tokens: ${POOL_TOKENS:list:["0x2f3A40A3db8a7e3D09B0adfEfbCe4f6F81927557","0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6","0xC04B0d3107736C32e19F1c62b2aF67BE61d63a05"]}
      managed_pool_address: ${MANAGED_POOL_ADDRESS:str:0xEe1a504F8BAdc2c0215119cb729B8B6a0ecB13a1}
      on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
      share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:true}
      service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a}
      consensus: &id002
        max_participants: 4
0:
  models:
    params:
      args:
        setup: *id001
        pool_tokens: ${POOL_TOKENS:list:["0x2f3A40A3db8a7e3D09B0adfEfbCe4f6F81927557","0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6","0xC04B0d3107736C32e19F1c62b2aF67BE61d63a05"]}
        managed_pool_address: ${MANAGED_POOL_ADDRESS:str:0xEe1a504F8BAdc2c0215119cb729B8B6a0ecB13a1}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:true}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a}
        consensus: *id002
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_0:str:node0:26656}
1:
  models:
    params:
      args:
        setup: *id001
        pool_tokens: ${POOL_TOKENS:list:["0x2f3A40A3db8a7e3D09B0adfEfbCe4f6F81927557","0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6","0xC04B0d3107736C32e19F1c62b2aF67BE61d63a05"]}
        managed_pool_address: ${MANAGED_POOL_ADDRESS:str:0xEe1a504F8BAdc2c0215119cb729B8B6a0ecB13a1}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:true}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a}
        consensus: *id002
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_1:str:node1:26656}
2:
  models:
    params:
      args:
        setup: *id001
        pool_tokens: ${POOL_TOKENS:list:["0x2f3A40A3db8a7e3D09B0adfEfbCe4f6F81927557","0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6","0xC04B0d3107736C32e19F1c62b2aF67BE61d63a05"]}
        managed_pool_address: ${MANAGED_POOL_ADDRESS:str:0xEe1a504F8BAdc2c0215119cb729B8B6a0ecB13a1}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:true}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a}
        consensus: *id002
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_2:str:node2:26656}
3:
  models:
    params:
      args:
        setup: *id001
        pool_tokens: ${POOL_TOKENS:list:["0x2f3A40A3db8a7e3D09B0adfEfbCe4f6F81927557","0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6","0xC04B0d3107736C32e19F1c62b2aF67BE61d63a05"]}
        managed_pool_address: ${MANAGED_POOL_ADDRESS:str:0xEe1a504F8BAdc2c0215119cb729B8B6a0ecB13a1}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:true}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a}
        consensus: *id002
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_3:str:node3:26656}
---
public_id: valory/ledger:0.19.0
type: connection
0:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_AUTONOMOUS_FUND_RPC_0:str:http://127.0.0.1:8545}
        chain_id: 5
1:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_AUTONOMOUS_FUND_RPC_1:str:http://127.0.0.1:8545}
        chain_id: 5
2:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_AUTONOMOUS_FUND_RPC_2:str:http://127.0.0.1:8545}
        chain_id: 5
3:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_AUTONOMOUS_FUND_RPC_3:str:http://127.0.0.1:8545}
        chain_id: 5
